In [1]:
import numpy as np
print(np.__version__)

2.4.2


In [8]:
arr = np.array([1,2,3,4,5])
print(arr, type(arr))
arr.shape

[1 2 3 4 5] <class 'numpy.ndarray'>


(5,)

- 데이터 분석 : 수치형 변수의 요약, 통계, 시각화
- 이미지처리 ai : 이미지데이터 
- 게임/시뮬레이션 : 시뮬레이션 구현
- 머신러닝/딥러닝 : 금융, 의료, 실험, 센서 데이터 

In [9]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("합계:", arr.sum())          # 21
print("평균:", arr.mean())         # 3.5
print("표준편차:", arr.std())      # 1.707825127659933
print("행 방향 합계:", arr.sum(axis=1))  # [6 15]
print("열 방향 평균:", arr.mean(axis=0))  # [2.5 3.5 4.5]
arr.shape

합계: 21
평균: 3.5
표준편차: 1.707825127659933
행 방향 합계: [ 6 15]
열 방향 평균: [2.5 3.5 4.5]


(2, 3)

In [11]:
arr = np.array ([10,10])
arr.shape

(2,)

In [13]:
arr = np.array([[10,10],[15,15]])
arr.shape

(2, 2)

In [14]:
arr= np.array([[[1,5,9],[2,6,10]],[[3,7,11],[4,8,12]]])
arr.shape

(2, 2, 3)

In [15]:
# 배열 생성
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# 배열의 속성 확인
print('배열의 차원:', arr.ndim)         # 2
print('배열의 형태:', arr.shape)        # (3, 3)
print('배열의 크기:', arr.size)         # 9
print('배열의 데이터 타입:', arr.dtype) # int64
print('배열 요소의 크기:', arr.itemsize) # 8 (바이트)
print('배열의 strides:', arr.strides)   # (24, 8)

배열의 차원: 2
배열의 형태: (3, 3)
배열의 크기: 9
배열의 데이터 타입: int64
배열 요소의 크기: 8
배열의 strides: (24, 8)


In [19]:
# 리스트로부터 배열 생성
arr1 = np.array([1, 2, 3, 4, 5]) #arr1.shape : (5,0)
arr12 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]) 
arr1.shape, arr12.shape

((5,), (2, 5))

In [20]:
# (3,5) 행렬 arr13 만들기
arr13 = np.array([
  [1,2,3,4,5],
  [6,7,8,9,10],
  [11,12,13,14,15]
])
arr13.shape

(3, 5)

In [22]:
np.arange(1, 16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [23]:
# 0으로 채워진 배열 생성
arr2 = np.zeros(5)

# 1로 채워진 배열 생성
arr3 = np.ones((3, 3))

# 1부터 10까지 2씩 증가하는 배열
range_arr = np.arange(1, 10, 2)  
print(range_arr)

 # 0부터 100까지 5개의 숫자를 균등 간격으로 생성
linspace_arr = np.linspace(0, 100, 5) 
print(linspace_arr)

# 2행 3열의 랜덤 값 배열 (0~1 사이)
random_arr = np.random.rand(2, 3) 
print(random_arr)

[1 3 5 7 9]
[  0.  25.  50.  75. 100.]
[[0.68202298 0.64039438 0.43476592]
 [0.13960695 0.85175049 0.21604269]]


# 넘파이의 데이터 타입

In [24]:
arr13.dtype

dtype('int64')

In [25]:
# 데이터 타입 변환 예제
float_arr = np.array([1.1, 2.2, 3.3])
int_arr = float_arr.astype(np.int32)  # 실수를 정수로 변환
print("변환 전:", float_arr, float_arr.dtype)
print("변환 후:", int_arr, int_arr.dtype)

변환 전: [1.1 2.2 3.3] float64
변환 후: [1 2 3] int32


In [26]:
arr_str = np.array(['1', '2', 'three'])  # 'three'는 숫자로 변환 불가
arr_int = arr_str.astype(int)  # 오류 발생

ValueError: invalid literal for int() with base 10: np.str_('three')

# 배열의 구조변경

In [27]:
# 1차원 배열 생성
a = np.arange(12)
print(a)  # [ 0  1  2  3  4  5  6  7  8  9 10 11]

# 2차원 배열로 변환 (3x4)
b = a.reshape(3, 4)
print(b)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# 3차원 배열로 변환 (2x2x3)
c = a.reshape(2, 2, 3)
print(c)
# [[[ 0  1  2]
#   [ 3  4  5]]
#  [[ 6  7  8]
#   [ 9 10 11]]]

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [31]:
data = [
  [120,135,150,145], #제품A
  [100,110,140,130], #제품B
  [90,100,95,105] #제품C
]
type(data)

list

In [32]:
# 생산량 합계 확인
total_production = [sum(product) for product in data]
total_production

[550, 480, 390]

In [33]:
prod_data = np.array(data)
prod_data

array([[120, 135, 150, 145],
       [100, 110, 140, 130],
       [ 90, 100,  95, 105]])

In [34]:
prod_data.shape

(3, 4)

In [36]:
np.sum(prod_data, axis=1)

array([550, 480, 390])

In [37]:
np.sum(prod_data, axis= 0)

array([310, 345, 385, 380])

In [38]:
profit_per_unit = np.array([20,30,25])


In [40]:
print(prod_data * profit_per_unit[:, np.newaxis])

[[2400 2700 3000 2900]
 [3000 3300 4200 3900]
 [2250 2500 2375 2625]]


In [41]:
total_produc = prod_data.sum(axis=1)

total_amt = total_produc * profit_per_unit
total_amt

array([11000, 14400,  9750])

In [42]:
# shape이 같은 배열 간의 연산
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("덧셈:\n", a + b)
print("뺄셈:\n", a - b)
print("곱셈:\n", a * b)
print("나눗셈:\n", a / b)

# shape이 다른 경우 오류 발생
c = np.array([[1, 2, 3], [4, 5, 6]])  # shape: (2, 3)
d = np.array([[1, 2], [3, 4]])        # shape: (2, 2)

# 이 연산은 오류를 발생시킴
# print(c + d)  # ValueError: operands could not be broadcast together

덧셈:
 [[ 6  8]
 [10 12]]
뺄셈:
 [[-4 -4]
 [-4 -4]]
곱셈:
 [[ 5 12]
 [21 32]]
나눗셈:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [43]:
# 비교 연산 예제
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([1, 3, 3, 0, 5])

# 같음 비교
print("같음:", arr1 == arr2)  # [ True False  True False  True]

# 크기 비교
print("더 큼:", arr1 > arr2)  # [False False False  True False]
print("더 작음:", arr1 < arr2)  # [False  True False False False]

# 논리 연산 결합
mask = (arr1 >= 3) & (arr2 <= 4)
print("복합 조건:", mask)  # [False False  True False False]

# 비교 결과를 이용한 필터링
filtered = arr1[arr1 > 3]
print("3보다 큰 값:", filtered)  # [4 5]

같음: [ True False  True False  True]
더 큼: [False False False  True False]
더 작음: [False  True False False False]
복합 조건: [False False  True  True False]
3보다 큰 값: [4 5]


In [44]:
# 요소별 연산 예제
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("요소별 덧셈:", a + b)      # [5 7 9]
print("요소별 곱셈:", a * b)      # [4 10 18]
print("요소별 제곱:", np.square(a))  # [1 4 9]
print("요소별 제곱근:", np.sqrt(a))  # [1. 1.41421356 1.73205081]

요소별 덧셈: [5 7 9]
요소별 곱셈: [ 4 10 18]
요소별 제곱: [1 4 9]
요소별 제곱근: [1.         1.41421356 1.73205081]


In [45]:
# 브로드캐스팅 예제
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
scalar = 2

# 배열과 스칼라의 연산
print("배열 * 스칼라:")
print(arr * scalar)
# [[ 2  4  6]
#  [ 8 10 12]]

배열 * 스칼라:
[[ 2  4  6]
 [ 8 10 12]]


In [46]:
# 1차원 배열과 2차원 배열의 연산
row = np.array([1, 0, 1])
print("\n2차원 배열 + 1차원 배열:")
print(arr + row)
# [[2 2 4]
#  [5 5 7]]


2차원 배열 + 1차원 배열:
[[2 2 4]
 [5 5 7]]


In [47]:
arr = np.array([0,1,2])
print(arr +5)

[5 6 7]


In [49]:
arr = np.ones((3,3)) + np.arange(3)
print(arr)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [51]:
arr = np.ones((3,1))+np.arange(3)
print(arr)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [61]:
a = np.arange(3).reshape(3, 1)
b = np.arange(3)
result = a + b
print(result)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


# 인덱싱과 슬라이싱

In [64]:
# 1차원 배열 인덱싱
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])    # 첫 번째 요소: 1
print(arr[-1])   # 마지막 요소: 5


1
5


In [65]:
# 2차원 배열 인덱싱
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(arr_2d[0, 1])    # 첫 번째 행, 두 번째 열: 2
print(arr_2d[1, -1])   # 두 번째 행, 마지막 열: 6

2
6


In [62]:
# 1차원 배열 슬라이싱
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr[2:5])    # [2 3 4]
print(arr[::2])    # [0 2 4]

[2 3 4]
[0 2 4]


In [63]:
# 2차원 배열 슬라이싱
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(arr_2d[:2, 1:3])    # 처음 두 행, 두 번째와 세 번째 열

[[2 3]
 [6 7]]


In [66]:
# 1차원 배열 인덱싱 예제
arr = np.array([10, 20, 30, 40, 50])

# 단일 요소 접근
print("첫 번째 요소:", arr[0])      # 10
print("마지막 요소:", arr[-1])      # 50

# 슬라이싱
print("처음부터 3개:", arr[:3])     # [10 20 30]
print("2번째부터 끝까지:", arr[2:]) # [30 40 50]
print("처음부터 끝까지 2단계씩:", arr[::2]) # [10 30 50]

첫 번째 요소: 10
마지막 요소: 50
처음부터 3개: [10 20 30]
2번째부터 끝까지: [30 40 50]
처음부터 끝까지 2단계씩: [10 30 50]


In [67]:
arr_2d = np.arange(16).reshape(4,4)
arr_2d

arr_2d[0] #[0, 1, 2, 3]
arr_2d[0, :] # 같은 코드
arr_2d[0, 1:3] # [1,2]
arr_2d[:2,:2] # [[0,1], [4,5]]

array([[0, 1],
       [4, 5]])

In [80]:
arr_3d = np.arange(36).reshape(6,6)
arr_3d_new = np.stack([arr_3d, arr_3d, arr_3d, arr_3d])
print(arr_3d_new)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [81]:
arr_3d_new[0,:3,:3]

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [82]:
# 불린 인덱싱 예제
arr = np.array([1, 2, 3, 4, 5])
bool_array = np.array([True, False, True, False, True])
print("불린 인덱싱:", arr[bool_array])  # [1 3 5]

불린 인덱싱: [1 3 5]


In [83]:
# 마스킹 예제
mask = arr > 3  # 조건식으로 마스크 생성
arr[mask] = 0   # 마스크를 사용한 값 수정
print("마스킹 결과:", arr)  # [1 2 3 0 0]

마스킹 결과: [1 2 3 0 0]


In [84]:
daily_returns = np.array([-0.01, 0.02, 0.05, -0.03, 0.01, 0.04, -0.02, -0.01, 0.03, 0.02, -0.05, 0.01, 0.00, 0.06])

In [85]:
daily_returns.shape

(14,)

In [86]:
daily_returns > 0

array([False,  True,  True, False,  True,  True, False, False,  True,
        True, False,  True, False,  True])

# 팬시인덱싱

In [87]:
indices = np.array([0,2,4]) #정수배열로 인덱싱
print(arr[indices])

[1 3 0]


In [88]:
import numpy as np

# -------------------------------
# 1. 가상의 주문 데이터 만들기
# -------------------------------
# 행(row): 주문
# 열(column): [고객ID, 상품카테고리, 주문금액, 할인여부, 배송완료여부]
#
# 상품카테고리 코드:
# 0 = 식품, 1 = 전자제품, 2 = 의류, 3 = 생활용품
#
# 할인여부:
# 0 = 할인 없음, 1 = 할인 적용
#
# 배송완료여부:
# 0 = 배송중, 1 = 배송완료

orders = np.array([
    [101, 0, 15000, 0, 1],
    [102, 1, 220000, 1, 1],
    [103, 2, 54000, 0, 0],
    [104, 1, 130000, 1, 1],
    [105, 3, 32000, 0, 1],
    [106, 2, 87000, 1, 0],
    [107, 0, 21000, 0, 1],
    [108, 1, 450000, 1, 0],
    [109, 3, 12000, 0, 1],
    [110, 2, 76000, 1, 1]
], dtype=int)

print("전체 주문 데이터:")
print(orders)
print()

# -------------------------------
# 2. 팬시 인덱싱: 특정 주문 행만 선택
# -------------------------------
# 예: 고객 CS 이슈가 생긴 주문 1, 4, 7번만 확인하고 싶다
target_order_idx = [1, 4, 7]

selected_orders = orders[target_order_idx]
print("CS 이슈 주문만 선택:")
print(selected_orders)
print()

# -------------------------------
# 3. 팬시 인덱싱: 특정 열만 선택
# -------------------------------
# 예: 고객ID와 주문금액만 보고 싶다
col_idx = [0, 2]

customer_and_amount = orders[:, col_idx]
print("고객ID와 주문금액만 선택:")
print(customer_and_amount)
print()

# -------------------------------
# 4. 팬시 인덱싱: 특정 행 + 특정 열 조합 선택
# -------------------------------
# 예: 2, 5, 8번 주문에서 고객ID와 배송완료여부만 보기
row_idx = [2, 5, 8]
col_idx = [0, 4]

subset = orders[np.ix_(row_idx, col_idx)]
print("특정 주문들의 고객ID와 배송완료여부:")
print(subset)
print()

# -------------------------------
# 5. 불리언 인덱싱(팬시 인덱싱 계열 실전 활용)
# -------------------------------
# 예: 전자제품(category=1) 주문만 찾기
electronics_orders = orders[orders[:, 1] == 1]
print("전자제품 주문만 선택:")
print(electronics_orders)
print()

# -------------------------------
# 6. 조건 여러 개 결합
# -------------------------------
# 예: 할인 적용된 주문 중 아직 배송완료 안 된 주문 찾기
mask = (orders[:, 3] == 1) & (orders[:, 4] == 0)

discount_not_delivered = orders[mask]
print("할인 적용 + 미배송 주문:")
print(discount_not_delivered)
print()

# -------------------------------
# 7. 팬시 인덱싱으로 값 일괄 수정
# -------------------------------
# 예: 특정 주문들(2, 5, 9번)에 추가 10% 할인 적용
# 주문금액 열은 index 2
promo_idx = [2, 5, 9]

print("할인 전 주문금액:", orders[promo_idx, 2])

orders[promo_idx, 2] = (orders[promo_idx, 2] * 0.9).astype(int)

print("할인 후 주문금액:", orders[promo_idx, 2])
print()

# -------------------------------
# 8. VIP 고객의 주문만 선택
# -------------------------------
# 예: VIP 고객 ID 목록이 따로 있을 때
vip_customers = np.array([102, 106, 110])

vip_mask = np.isin(orders[:, 0], vip_customers)
vip_orders = orders[vip_mask]

print("VIP 고객 주문:")
print(vip_orders)
print()

# -------------------------------
# 9. 가장 많이 보는 실전 패턴:
# 특정 행에서 특정 열을 각각 짝지어 뽑기
# -------------------------------
# 예: 0, 3, 7번 주문에서
# 각각 [고객ID, 주문금액, 배송완료여부] 중 하나씩 개별적으로 뽑고 싶을 때
#
# (0번 주문의 고객ID), (3번 주문의 주문금액), (7번 주문의 배송완료여부)
rows = np.array([0, 3, 7])
cols = np.array([0, 2, 4])

picked_values = orders[rows, cols]
print("행-열 짝지어서 선택한 값:")
print(picked_values)
print()

# -------------------------------
# 10. 보기 좋게 해석 출력
# -------------------------------
category_map = {
    0: "식품",
    1: "전자제품",
    2: "의류",
    3: "생활용품"
}

print("VIP 주문 해석:")
for order in vip_orders:
    customer_id = order[0]
    category = category_map[order[1]]
    amount = order[2]
    discount = "Y" if order[3] == 1 else "N"
    delivered = "완료" if order[4] == 1 else "배송중"

    print(f"고객 {customer_id} | 카테고리: {category} | 주문금액: {amount:,}원 | 할인: {discount} | 배송: {delivered}")

전체 주문 데이터:
[[   101      0  15000      0      1]
 [   102      1 220000      1      1]
 [   103      2  54000      0      0]
 [   104      1 130000      1      1]
 [   105      3  32000      0      1]
 [   106      2  87000      1      0]
 [   107      0  21000      0      1]
 [   108      1 450000      1      0]
 [   109      3  12000      0      1]
 [   110      2  76000      1      1]]

CS 이슈 주문만 선택:
[[   102      1 220000      1      1]
 [   105      3  32000      0      1]
 [   108      1 450000      1      0]]

고객ID와 주문금액만 선택:
[[   101  15000]
 [   102 220000]
 [   103  54000]
 [   104 130000]
 [   105  32000]
 [   106  87000]
 [   107  21000]
 [   108 450000]
 [   109  12000]
 [   110  76000]]

특정 주문들의 고객ID와 배송완료여부:
[[103   0]
 [106   0]
 [109   1]]

전자제품 주문만 선택:
[[   102      1 220000      1      1]
 [   104      1 130000      1      1]
 [   108      1 450000      1      0]]

할인 적용 + 미배송 주문:
[[   106      2  87000      1      0]
 [   108      1 450000      1      0]]

할인 전 주문금액